import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { FileSpreadsheet, Download, Sparkles, Check, Loader2, AlertCircle } from 'lucide-react';
import { safeFetch } from '../../utils/api';

export const AdminReportsPage: React.FC = () => {
  const { user, token } = useAuth();
  const [reportType, setReportType] = useState('traffic');
  const [dateRange, setDateRange] = useState('30d');
  const [generating, setGenerating] = useState(false);
  const [reportError, setReportError] = useState<string | null>(null);

  const handleGenerateReport = async () => {
    setGenerating(true);
    setReportError(null);
    try {
      const res = await safeFetch<any>(`/api/admin/reports/data?type=${reportType}&range=${dateRange}`, {
        headers: { Authorization: `Bearer ${token}` }
      });

      if (!res.ok || !res.data?.success) {
        throw new Error(res.error || 'Failed to aggregate report data from database');
      }

      const rows = res.data?.rows || [];
      const csvHeader = `ORILLUSIVE EXECUTIVE REPORT\nGenerated By: ${user?.name || 'Administrator'} (${user?.role || 'SUPER_ADMIN'})\nGenerated At: ${new Date().toISOString()}\nReport Focus: ${reportType.toUpperCase()}\nTime Period: ${dateRange}\n\nMetric,Value\n`;
      const csvBody = rows.map((r: any) => `"${r.metric}","${r.value}"`).join('\n');
      const csvData = csvHeader + csvBody + '\n';

      const blob = new Blob([csvData], { type: 'text/csv;charset=utf-8;' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Orillusive_${reportType}_report_${Date.now()}.csv`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (err: any) {
      console.error('[REPORT GENERATION ERROR]', err);
      setReportError(err?.message || 'Error generating report from database');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 font-sans">
      <div className="flex items-center justify-between border-b border-white/10 pb-5">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <FileSpreadsheet className="size-6 text-[#C9A84C]" />
            <span>Executive Report Generator</span>
          </h1>
          <p className="text-xs text-[#888888] mt-1">
            Generate branded executive performance, traffic, technical error, and subscription revenue reports.
          </p>
        </div>
      </div>

      {reportError && (
        <div className="p-4 rounded-2xl bg-red-500/10 border border-red-500/30 text-red-300 text-xs flex items-center gap-3 max-w-xl">
          <AlertCircle className="size-4 text-red-400 shrink-0" />
          <span>{reportError}</span>
        </div>
      )}

      <div className="p-8 rounded-3xl bg-[#141414] border border-white/10 max-w-xl space-y-6">
        <div>
          <label className="block text-xs font-mono uppercase text-[#888888] mb-2">Report Focus Area:</label>
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full bg-[#1C1C1C] border border-white/15 text-xs text-white p-3 rounded-xl focus:outline-none"
          >
            <option value="traffic">Website Traffic & Audience Engagement</option>
            <option value="performance">Technical Performance & Latency Telemetry</option>
            <option value="subscriptions">Subscriptions & Credit Monetization</option>
            <option value="issues">Technical Errors & Resolution SLA</option>
          </select>
        </div>

        <div>
          <label className="block text-xs font-mono uppercase text-[#888888] mb-2">Time Period:</label>
          <select
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
            className="w-full bg-[#1C1C1C] border border-white/15 text-xs text-white p-3 rounded-xl focus:outline-none"
          >
            <option value="7d">Last 7 Days</option>
            <option value="30d">Last 30 Days</option>
            <option value="90d">Last 90 Days</option>
            <option value="year">Year to Date</option>
          </select>
        </div>

        <button
          disabled={generating}
          onClick={handleGenerateReport}
          className="w-full py-3.5 rounded-2xl bg-[#4F6B85] hover:bg-[#3B5268] text-white font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-md transition-all disabled:opacity-50"
        >
          {generating ? (
            <>
              <Loader2 className="size-4 animate-spin text-[#C9A84C]" />
              <span>Generating Executive Report...</span>
            </>
          ) : (
            <>
              <Download className="size-4 text-[#C9A84C]" />
              <span>Generate & Download CSV Report</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};

export default AdminReportsPage;
