import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { FileSpreadsheet, Download, Sparkles, Check, Loader2 } from 'lucide-react';

export const AdminReportsPage: React.FC = () => {
  const { user } = useAuth();
  const [reportType, setReportType] = useState('traffic');
  const [dateRange, setDateRange] = useState('30d');
  const [generating, setGenerating] = useState(false);

  const handleGenerateReport = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);

      // Trigger CSV Report File Download
      const csvData = `ORILLUSIVE EXECUTIVE REPORT\nGenerated By: ${user?.name} (${user?.role})\nDate: ${new Date().toISOString()}\nReport Type: ${reportType.toUpperCase()}\nDate Range: ${dateRange}\n\nMetric,Value\nTotal Visitors,14280\nUnique Visitors,9840\nPage Views,38450\nConversion Rate,4.2%\nSystem Uptime,99.98%\n`;
      const blob = new Blob([csvData], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Orillusive_${reportType}_report_${Date.now()}.csv`;
      a.click();
    }, 1000);
  };

  return (
    <div className="space-y-6 font-sans">
      <div className="flex items-center justify-between border-b border-white/10 pb-5">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <FileSpreadsheet className="size-6 text-[#C9A84C]" />
            <span>Executive Report Generator</span>
          </h1>
          <p className="text-xs text-[#888888] mt-1">
            Generate branded executive performance, traffic, technical error, and subscription revenue reports.
          </p>
        </div>
      </div>

      <div className="p-8 rounded-3xl bg-[#141414] border border-white/10 max-w-xl space-y-6">
        <div>
          <label className="block text-xs font-mono uppercase text-[#888888] mb-2">Report Focus Area:</label>
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full bg-[#1C1C1C] border border-white/15 text-xs text-white p-3 rounded-xl focus:outline-none"
          >
            <option value="traffic">Website Traffic & Audience Engagement</option>
            <option value="performance">Technical Performance & Latency Telemetry</option>
            <option value="subscriptions">Subscriptions & Credit Monetization</option>
            <option value="issues">Technical Errors & Resolution SLA</option>
          </select>
        </div>

        <div>
          <label className="block text-xs font-mono uppercase text-[#888888] mb-2">Time Period:</label>
          <select
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
            className="w-full bg-[#1C1C1C] border border-white/15 text-xs text-white p-3 rounded-xl focus:outline-none"
          >
            <option value="7d">Last 7 Days</option>
            <option value="30d">Last 30 Days</option>
            <option value="90d">Last 90 Days</option>
            <option value="year">Year to Date</option>
          </select>
        </div>

        <button
          disabled={generating}
          onClick={handleGenerateReport}
          className="w-full py-3.5 rounded-2xl bg-[#4F6B85] hover:bg-[#3B5268] text-white font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-md transition-all disabled:opacity-50"
        >
          {generating ? (
            <>
              <Loader2 className="size-4 animate-spin text-[#C9A84C]" />
              <span>Generating Executive Report...</span>
            </>
          ) : (
            <>
              <Download className="size-4 text-[#C9A84C]" />
              <span>Generate & Download CSV Report</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};

export default AdminReportsPage;
